version = 1

test_patterns = ["**/*_test.go"]

[[analyzers]]
name = "sql"
enabled = true

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/TunnelWork/Ulysses.Lib"

[[transformers]]
name = "gofmt"
enabled = true